# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-11 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.IntegerField(max_length=20)),
                ('telefone', models.IntegerField(max_length=20)),
                ('ender', models.CharField(max_length=120)),
            ],
        ),
    ]
