# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-11 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180611_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
