# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-11 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0009_auto_20180611_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=120)),
                ('dt_nasc', models.DateField()),
                ('cpf', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('ender', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('dt_nasc', models.DateField()),
                ('cpf', models.IntegerField()),
                ('tel', models.IntegerField()),
                ('ender', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_emp', models.DateField()),
                ('cod_at', models.ManyToManyField(to='blog.Atendente')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('isbn', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='cod_li',
            field=models.ManyToManyField(to='blog.Livro'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='matricula',
            field=models.ManyToManyField(to='blog.Aluno'),
        ),
    ]
