# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-11 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180611_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='cod_at',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='cod_li',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='matricula',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Atendente',
        ),
        migrations.DeleteModel(
            name='Emprestimo',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
