# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-12 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180611_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='cod_at',
            new_name='atendente',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='cod_li',
            new_name='livro',
        ),
    ]
